export const state = {
  userId: '',
  courses: [],
  pollingTimer: null,
  autoPollingTimer: null,
  currentPage: 'dashboard',
  lastPlayerStatus: '',
  autoScheduleHours: [9, 13, 18, 23],
  autoEnabled: false,
  currentTerm: '',
  selectedTerm: null,   // null = 현재 학기
  currentCourseId: '',
  currentCourseName: '',
  currentSummaryId: '',
  downloadTaskTimers: {},
  settings: {
    DOWNLOAD_ENABLED: 'false',
    DOWNLOAD_RULE: 'mp4',
    DOWNLOAD_DIR: '',
    AUTO_DOWNLOAD_AFTER_PLAY: 'false',
    STT_ENABLED: 'false',
    AI_ENABLED: 'false',
  },
  settingsLoaded: false,
  autoDownloadStartedFor: '',
};
